"use client";

import { useContext } from "react";
import { ChatContext } from "./chatState";
import Head from "next/head";
import ChatList from "./components/ChatList";
import ChatWindow from "./components/ChatWindow";
import ChatDetails from "./components/ChatDetails";
import SearchableDropdown from "./components/DropDown";

export default function Home() {
  const { state, dispatch } = useContext(ChatContext);
  console.log(state);

  return (
    <div className="h-screen flex items-center justify-center bg-custom-bg-gray">
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen shadow-xl  flex">
        {/* Левая панель с чатом */}
        <ChatList />
        {/*<SearchableDropdown />*/}

        {/* Правая панель с сообщениями */}
        <ChatWindow />
        <ChatDetails />
      </main>
    </div>
  );
}
