"use client";

import { useContext } from "react";
import { ChatContext } from "./chatState";
import Head from "next/head";
import ChatList from "./components/ChatList";
import ChatWindow from "./components/ChatWindow";
import ChatDetails from "./components/ChatDetails";
import SearchableDropdown from "./components/DropDown";

export default function Home() {
  const { state, dispatch } = useContext(ChatContext);
  console.log(state);

  return (
    <div className="h-screen flex items-center justify-center bg-custom-bg-gray">
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen shadow-xl  flex">
        {/* Левая панель с чатом */}
        <ChatList />
        {/*<SearchableDropdown />*/}

        {/* Правая панель с сообщениями */}
        <ChatWindow />
        <ChatDetails />
      </main>
    </div>
  );
}

//"subject-tema": "Тестовая тема из Redux",
//reply_on_message: JSON.stringify({
//id: 789,
//text: "Оригинальное сообщение из Redux",
//channel_name: "email",
//}),


applyFilters(state) {
  {
    /*const { vacancies, recruiters, clients } = action.payload;
  state.filteredChats = state.chats.filter((chat) => {
    const matchesVacancy = vacancies.length
      ? vacancies.includes(chat.vacancy)
      : true;
    const matchesRecruiter = recruiters.length
      ? recruiters.includes(chat.recruiter)
      : true;
    const matchesClients = clients.length
      ? clients.some((client) => chat.clients?.includes(client))
      : true;
    return matchesVacancy && matchesRecruiter && matchesClients;
  }); 
  }
  state.appliedFilters = Object.values(state.selectedFilters).filter(
    (arr) => arr.length > 0
  ).length;
},
