"use client";

//import { ChatProvider } from "./chatState";
import { Provider } from "react-redux";
import store from "./store";

import { inter } from "./ui/font";
import "./globals.css";

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>{children}</body>
      </html>
    </Provider>
  );
}
