"use client";

import { useContext } from "react";
import { ChatContext } from "./chatState";
import Head from "next/head";
import ChatList from "./components/ChatList";
import ChatWindow from "./components/ChatWindow";
import ChatDetails from "./components/ChatDetails";
import LoginForm from "./components/LoginForm";
import TestSocket from "./components/TestSocket";

export default function Home() {
  return (
    <div className="h-screen flex items-center justify-center bg-custom-bg-gray">
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen shadow-xl  flex items-center justify-center">
        <div className="flex items-center justify-center">
          <LoginForm />
          {/*<TestSocket />*/}
        </div>
      </main>
    </div>
  );
}
