// selectStyles.js

export const customSelectStyles = {
  multiValue: (provided) => ({
    ...provided,
    display: "flex",
    justifyContent: "flex-start",
    //justifyItems: "center",
    alignItems: "center",
    //textAlign: "center",
    backgroundColor: "#f9f9f9",
    borderRadius: "0.375rem",
    padding: 0,
    margin: 0,
    marginRight: "4px",
    marginTop: "4px",
    marginBottom: "4px",
    border: "1px solid #94A3B8",
    overflow: "hidden",
  }),
  placeholder: (base, state) => ({
    ...base,
    color: "#CACACA",
    fontSize: "15px",
  }),
  multiValueLabel: (provided) => ({
    ...provided,
    //marginRight: "mr-2",
    //marginLeft: "1px",
    color: "#64748B",
    fontSize: "13px",
    //justifyContent: "left",
    //textAlign: "left !important",
    //items: "center",
    margin: 0,
    padding: 0,
    paddingTop: "2px",
    //paddingLeft: "4px",
    paddingRight: "5px",
    paddingLeft: "4px",
    paddingBottom: "2px",
    backgroundColor: "white",
    borderRight: "1px solid #94A3B8",
    borderRadius: 0,
    justifyContent: "center",
    //margin: "1px",
  }),
  multiValueRemove: (provided) => ({
    ...provided,
    cursor: "pointer",
    color: "gray-500",
  }),
  control: (provided, state) => ({
    ...provided,
    margin: 0,
    padding: 0,
    paddingLeft: "0px",
    outline: "none",
    border: "custom-bg-gray",
    boxShadow: "none",
    backgroundColor: "white", // Изменение фона в зависимости от наличия значения
    //borderColor: state.isFocused ? "#789CCC" : "#F1F5F9",
    //"&:hover": {
    //borderColor: state.isHovered ? "#789CCC" : "inherit", // Изменение фона при наведении курсора
    //},
    //borderColor: "#F1F5F9",
    "&:focus": {
      outline: "none",
      boxShadow: "none",
      //borderColor: "#789CCC",
    },
  }),
  dropdownIndicator: (provided) => ({
    ...provided,
    display: "none",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
};
